# Generated by Django 5.1.7 on 2025-03-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='T001IdAutor', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('biografia', models.CharField(blank=True, db_column='T001Documento', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001',
            },
        ),
    ]
