# Generated by Django 5.1.7 on 2025-03-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libreria', '0002_editorial_alter_autor_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, db_column='T001Biografia', null=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.CharField(blank=True, db_column='T002Telefono', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_Libro', models.AutoField(db_column='T003IdLibro', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T003Titulo', max_length=100)),
                ('resumen', models.TextField(db_column='T003Resumen')),
                ('isbn', models.CharField(db_column='T003ISBN', max_length=20, unique=True)),
                ('fecha_publicacion', models.DateField(db_column='T003Fecha_Publicacion')),
                ('autor', models.ForeignKey(db_column='T001IdAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_libreria.autor')),
                ('editorial', models.ForeignKey(db_column='T002IdEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_libreria.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T003',
            },
        ),
    ]
