# Generated by Django 5.1.7 on 2025-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libreria', '0003_alter_autor_biografia_alter_editorial_telefono_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id_miembro', models.AutoField(db_column='T004IdEditorial', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T004Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T004Direccion', max_length=100)),
                ('email', models.CharField(db_column='T004Telefono', max_length=50)),
                ('fecha_membresia', models.DateField(db_column='T004Fecha_Membresia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T004',
            },
        ),
    ]
