# Generated by Django 5.1.7 on 2025-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libreria', '0004_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='apellido',
            field=models.CharField(db_column='T004Apellido', max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='email',
            field=models.CharField(db_column='T004Email', max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='id_miembro',
            field=models.AutoField(db_column='T004IdMiembro', editable=False, primary_key=True, serialize=False),
        ),
    ]
