# Generated by Django 5.1.7 on 2025-03-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_libreria', '0005_alter_miembro_apellido_alter_miembro_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='T005IdPrestamo', editable=False, primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='T005Fecha_Prestamo')),
                ('fecha_devolucion', models.DateField(blank=True, db_column='T005Fecha_Devolucion', null=True)),
                ('libro', models.ForeignKey(db_column='T003IdLibro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_libreria.libro')),
                ('mode', models.ForeignKey(db_column='T004IdMiembro', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='api_libreria.miembro')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T005',
            },
        ),
    ]
