# Generated by Django 5.1.7 on 2025-03-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_libreria', '0006_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='id_Libro',
            new_name='id_libro',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='mode',
            new_name='miembro',
        ),
    ]
